name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 4 * * *' # run at 4 AM UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup SQLCipher
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ];
          then
            sudo apt-get update
            sudo apt-get install libxml2-utils wget
            wget -q https://raw.githubusercontent.com/rotki/rotki/develop/install_deps.sh -O install_deps.sh
            chmod u+x install_deps.sh
            ./install_deps.sh
            rm install_deps.sh
            sudo ldconfig
          fi
          if [ ${{ matrix.os }} == 'macos-latest' ];
          then
            brew install sqlcipher
          fi
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pylint pytest mypy==0.790 pycodestyle
      - name: Typecheck & Lint
        run: |
          pylint --version
          mypy --version
          py.test --version
          make lint typecheck
      - name: Test with pytest
        run: pytest -vv --maxfail=2
